title: BrightShard
email: brightshard@brightshard.dev
description: >-
  My open-source projects and blog.
source: frontend/
url: "https://brightshard.dev"

# Catch all errors at build-time
liquid:
  error_mode: strict
  strict_filters: true
strict_front_matter: true

# SCSS/SASS config
sass:
  style: compressed

api_url: 127.0.0.1:8000
