title: BrightShard
email: brightshard@brightshard.dev
description: >-
  My open-source projects and blog.
source: frontend/
url: "https://brightshard.dev"

# Catch all errors at build-time
liquid:
  error_mode: strict
  strict_filters: true
strict_front_matter: true

# SCSS/SASS config
sass:
  style: compressed

api_url: 127.0.0.1:8000

departments:
  - name: Cardiology
    id: cardiology
  - name: Ear, Nose, & Throat
    id: ent
  - name: General Surgery
    id: surgery
  - name: Neurology
    id: neurology
  - name: Nutrition & Dietetics
    id: nutrition
  - name: Oncology
    id: oncology
  - name: Orthopedics
    id: orthopedics
  - name: Reproductive Health
    id: reproductive

doctors:
  - name: Carpenter
    department: cardiology
    description: Cardiologist.
  - name: Taka
    department: cardiology
  - name: Roberts
    department: ent
  - name: Veratti
    department: ent
  - name: Benzema
    department: surgery
  - name: Rashford
    department: surgery
  - name: Taylor
    department: neurology
  - name: Leao
    department: neurology
  - name: Alfred
    department: nutrition
  - name: Larry
    department: orthopedics
  - name: Lorenzo
    department: orthopedics
  - name: Green
    department: oncology
  - name: Wilson
    department: oncology
  - name: Gerard
    department: orthopedics
  - name: Hill
    department: reproductive
  - name: Stefany
    department: reproductive
